[libraries]
api = { module = "de.robv.android.xposed:api", version = "82" }
core-ktx = { group = "androidx.core", name = "core-ktx", version = "1.17.0" }
activity = { group = "androidx.activity", name = "activity-compose", version = "1.12.3" }
viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version = "2.10.0" }
viewmodel-savedstate = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-savedstate", version = "2.10.0" }
compose-foundation = { group = "androidx.compose.foundation", name = "foundation", version = "1.10.2" }
preference = { group = "me.zhanghai.compose.preference", name = "library", version = "1.1.1" }
material3 = { group = "androidx.compose.material3", name = "material3", version = "1.5.0-alpha13" }
material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended", version = "1.7.8" }
libsu = { group = "com.github.topjohnwu.libsu", name = "core", version = "6.0.0" }
documentfile = { group = "androidx.documentfile", name = "documentfile", version = "1.1.0" }
hiddenapibypass = { group = "org.lsposed.hiddenapibypass", name = "hiddenapibypass", version = "+" }
navigation = { group = "androidx.navigation", name = "navigation-compose", version = "2.9.7" }
reorderable = { module = "sh.calvin.reorderable:reorderable", version = "3.0.0" }
ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version = "1.10.2" }
ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version = "1.10.2" }

#junit = { group = "junit", name = "junit", version.ref = "junit" }
#ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
#espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }

[plugins]
android-application = { id = "com.android.application", version = "9.0.0" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version = "2.3.0" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version = "2.3.0" }
dependency-license-report = { id = "com.github.jk1.dependency-license-report", version = "3.0.1" }
